version: "3"

services:
  db:
    image: postgres:12.3-alpine
    container_name: todo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - PGPASSWORD=test
      - POSTGRES_DB=test
      - DATABASE_HOST=localhost
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
